author: Ramon de C Valle
baseurl: /jekyll-theme-semantic
description: A Semantic UI -based Jekyll theme.
exclude:
  - "*.gemspec"
  - "CONTRIBUTING*"
  - Gemfile
  - Gemfile.lock
  - "LICENSE*"
  - "README*"
  - node_modules
  - vendor
keywords: jekyll, theme, semantic, semantic-ui
name: jekyll-theme-semantic
paginate: 3
paginate_path: /pages/:num/
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate
url: https://rcvalle.github.io
